const entry_points = require("./entry-points").get()
module.exports.get = () => [
  {
    slot_num: 1,
    new_entry_point: entry_points[0],
    size: "SP",
    occopied: null,
    allowed_vehicle_size: ["S"],
  },
  {
    slot_num: 2,
    new_entry_point: entry_points[0],
    size: "MP",
    occopied: null,
    allowed_vehicle_size: ["S", "M"],
  },
  {
    slot_num: 3,
    new_entry_point: entry_points[0],
    size: "LP",
    occopied: null,
    allowed_vehicle_size: ["S", "M", "L"],
  },
  {
    slot_num: 4,
    new_entry_point: entry_points[0],
    size: "SP",
    occopied: null,
    allowed_vehicle_size: ["S"],
  },
  {
    slot_num: 5,
    new_entry_point: entry_points[0],
    size: "MP",
    occopied: null,
    allowed_vehicle_size: ["S", "M"],
  },
  {
    slot_num: 6,
    new_entry_point: entry_points[0],
    size: "LP",
    occopied: null,
    allowed_vehicle_size: ["S", "M", "L"],
  },
  {
    slot_num: 7,
    new_entry_point: entry_points[1],
    size: "SP",
    occopied: null,
    allowed_vehicle_size: ["S"],
  },
  {
    slot_num: 8,
    new_entry_point: entry_points[1],
    size: "MP",
    occopied: null,
    allowed_vehicle_size: ["S", "M"],
  },
  {
    slot_num: 9,
    new_entry_point: entry_points[1],
    size: "LP",
    occopied: null,
    allowed_vehicle_size: ["S", "M", "L"],
  },
  {
    slot_num: 10,
    new_entry_point: entry_points[1],
    size: "SP",
    occopied: null,
    allowed_vehicle_size: ["S"],
  },
  {
    slot_num: 11,
    new_entry_point: entry_points[1],
    size: "MP",
    occopied: null,
    allowed_vehicle_size: ["S", "M"],
  },
  {
    slot_num: 12,
    new_entry_point: entry_points[1],
    size: "LP",
    occopied: null,
    allowed_vehicle_size: ["S", "M", "L"],
  },
  {
    slot_num: 13,
    new_entry_point: entry_points[2],
    size: "SP",
    occopied: null,
    allowed_vehicle_size: ["S"],
  },
  {
    slot_num: 14,
    new_entry_point: entry_points[2],
    size: "MP",
    occopied: null,
    allowed_vehicle_size: ["S", "M"],
  },
  {
    slot_num: 15,
    new_entry_point: entry_points[2],
    size: "LP",
    occopied: null,
    allowed_vehicle_size: ["S", "M", "L"],
  },
  {
    slot_num: 16,
    new_entry_point: entry_points[2],
    size: "SP",
    occopied: null,
    allowed_vehicle_size: ["S"],
  },
  {
    slot_num: 17,
    new_entry_point: entry_points[2],
    size: "MP",
    occopied: null,
    allowed_vehicle_size: ["S", "M"],
  },
  {
    slot_num: 18,
    new_entry_point: entry_points[2],
    size: "LP",
    occopied: null,
    allowed_vehicle_size: ["S", "M", "L"],
  },
];